apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-info-app
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sys-info
  template:
    metadata:
      labels:
        app: sys-info
    spec:
      containers:
      - name: monitor
        image: ghcr.io/eyalvoulichman-source/sys-info-app:latest
        ports:
        - containerPort: 8080
        # כאן אנחנו מחברים את הדיסק לתיקייה בתוך הקונטיינר
        volumeMounts:
        - name: temp-cache
          mountPath: /tmp/app-data
      # כאן אנחנו מגדירים את הדיסק עצמו
      volumes:
      - name: temp-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sys-info-service
  namespace: devops
spec:
  selector:
    app: sys-info
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sys-info-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sys-info.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sys-info-service
            port:
              number: 80